FROM golang:1.22-alpine

RUN apk --no-cache add ca-certificates gcc musl-dev linux-headers
WORKDIR /go/src/github.com/GenesisEducationKyiv/software-engineering-school-4-0-Hukyl/email-service
COPY go.mod go.sum ./
RUN go mod download && go mod verify
COPY . .
ENV GOCACHE=/root/.cache/go-build
RUN --mount=type=cache,target="/root/.cache/go-build" CGO_ENABLED=1 GOOS=linux go build -o /email-service ./cmd/main.go

ENTRYPOINT ["go", "test", "-v", "./..."]
