name: Unit testing

on: [push]

jobs:

  unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Test API service
      run: go test -v ./...
      working-directory: ./currency-rate

    - name: Test email service
      run: go test -v ./...
      working-directory: ./email-service
